name: Deploy Next.js App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.5.0

      - name: Install NPM packages
        run: yarn install

      - name: Build Next.js App
        run: yarn build

      - name: Export Next.js app
        run: yarn export

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /home/${{ secrets.FTP_USERNAME }}/www/
          protocol: ftps
